namespace Nova.Security;

public sealed class UserAutoGeneratedPasswordEncryptor : TextEncryptorBase
{
    public UserAutoGeneratedPasswordEncryptor(ITextEncryptionKeyLoader keyLoader) : base(keyLoader)
    {
    }
}

public sealed class UserAutoGeneratedPasswordDecryptor : TextDecryptorBase
{
    public UserAutoGeneratedPasswordDecryptor(ITextDecryptionKeyLoader keyLoader) : base(keyLoader)
    {
    }
}

sealed class PemFileUserAutoGeneratedPasswordEncryptionKeyLoader : PemFileTextCryptoKeyLoaderBase, ITextEncryptionKeyLoader
{
    public PemFileUserAutoGeneratedPasswordEncryptionKeyLoader(string filePath) : base(filePath)
    {
    }
}

sealed class PemFileUserAutoGeneratedPasswordDecryptionKeyLoader : PemFileTextCryptoKeyLoaderBase, ITextDecryptionKeyLoader
{
    public PemFileUserAutoGeneratedPasswordDecryptionKeyLoader(string filePath) : base(filePath)
    {
    }
}